### ISSUE TITLE
Add ability to generate numbered shortcuts for connections

### ISSUE THREAD

**Issue by lku** [MHMcz/remote-manager#1]
It would be nice if there are generated numbers for all connections in configuration for quick selection. Something like this:

``` sh
$ devel
===========================================
 - 1: example: example.cz
 - 2: home: example.cz
 - 2: server: example.cz
===========================================
```

**Comment by MHMcz** [comment]
Problem was what to do with collisions, when there is numeral alias in config. This "duplicate" numbers are skipped.

**Comment by lku** [comment]
:+1: It works like a charm! And thanks for the oh-my-zsh plugin!
